# Generated by Django 5.0.7 on 2024-12-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students_course', to='main.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers_room', to='main.room'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers_science', to='main.science'),
        ),
    ]
