# Generated by Django 5.0.7 on 2024-12-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_course_alter_teacher_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='science',
        ),
        migrations.AddField(
            model_name='science',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teachers_science', to='main.teacher'),
            preserve_default=False,
        ),
    ]
