# Generated by Django 5.0.7 on 2024-12-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_science_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='science',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.science'),
            preserve_default=False,
        ),
    ]
