# Generated by Django 5.0.7 on 2024-12-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_teacher_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.science'),
        ),
    ]
