# Generated by Django 5.0.7 on 2024-12-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_course', to='main.teacher'),
        ),
    ]
