# Generated by Django 5.0.7 on 2024-12-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_student_diary_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_diary',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
