# Generated by Django 5.0.7 on 2024-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_student_diary_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_list',
            name='teachers',
        ),
        migrations.AddField(
            model_name='lesson_list',
            name='Science',
            field=models.ManyToManyField(to='main.science'),
        ),
    ]
